---
title: Simple Model Comparison - One Sample T-Test
jupyter: python3
---


_Author: Šimon Kucharský_


In this notebook, we will show how to do a simple model comparison in BayesFlow amortized over the number of observations.

Amortized Bayesian model comparison leverages neural networks to learn a mapping from data to posterior model probabilities, effectively bypassing the need for costly inference procedures for each new dataset. 

The method is particularly useful in scenarios where model evaluation needs to be performed repeatedly, as the inference cost is front-loaded into the training phase, enabling rapid comparisons at test time.

```{python}
#| ExecuteTime: {end_time: '2025-04-26T02:34:13.774900Z', start_time: '2025-04-26T02:34:11.487313Z'}
import os

if "KERAS_BACKEND" not in os.environ:
    # set this to "torch", "tensorflow", or "jax"
    os.environ["KERAS_BACKEND"] = "tensorflow"
```

```{python}
import numpy as np
import keras

import bayesflow as bf
```

## Simulator

First we define our simulators, one for every model that we want to compare. In this notebook, we will use two simple models

$$
\begin{aligned}
\mathcal{M}_0: \mu & = 0 \\
\mathcal{M}_1: \mu & \sim \text{Normal}(0, 1) \\ 
\\
n & \sim \text{Uniform}(10, 100) \\
x_i & \sim \text{Normal}(\mu, 1) \text{ for } i \in \{1, \dots, n \} \\
\end{aligned}
$$

Each model has their own prior but the likelihood (that is responsible for simulating the data $x$) remains the same for both models.

Once we define the two simulators, we wrap them in one overarching simulator that simulates from both models at the same time, for the purpose of training the networks from either of the models. Our context variable $n$ is the _sample size_ that we amortize over as is used as a shared simulator for both models, so that data within each simulated batch can consist of simulations from either model, buth with the same sample size.

```{python}
#| ExecuteTime: {end_time: '2025-04-26T02:34:13.780691Z', start_time: '2025-04-26T02:34:13.777756Z'}
def context(batch_shape, n=None):
    if n is None:
        n = np.random.randint(20, 30)
    return dict(n=n)

def prior_null():
    return dict(mu=0.0)

def prior_alternative():
    mu = np.random.normal(loc=0, scale=1)
    return dict(mu=mu)

def likelihood(n, mu):
    x = np.random.normal(loc=mu, scale=1, size=n)
    return dict(x=x)
```

```{python}
simulator_null = bf.make_simulator([prior_null, likelihood])

simulator_alternative = bf.make_simulator([prior_alternative, likelihood])

simulator = bf.simulators.ModelComparisonSimulator(
    simulators=[simulator_null, simulator_alternative], 
    use_mixed_batches=True, 
    shared_simulator=context,
)
```

Now we can simulate some data to see what the simulator produces.

```{python}
#| ExecuteTime: {end_time: '2025-04-26T02:34:13.840198Z', start_time: '2025-04-26T02:34:13.837161Z'}
data = simulator.sample(100)
print("n =", data["n"])
for key, value in data.items():
    print(key + " shape:", np.array(value).shape)
```

Notice that the simulator automaticall adds `model_indices`, which indicates which data was generated which model (it is one-hot encoded, therefore will have as many columns as models).

The size of the observations `x` depends on the context variable `n`. 

## Defining the neural networks

To ensure that the training data generated by the simulator can be used for deep learning, we have to do some transformations that will put the data into necessary structures. Here, we will define an `adapter` that takes the data and transforms the input.

```{python}
#| ExecuteTime: {end_time: '2025-04-26T02:34:13.884625Z', start_time: '2025-04-26T02:34:13.882973Z'}
adapter = (
    bf.Adapter()
    .sqrt("n")
    .broadcast("n", to="x")
    .as_set("x")
    .rename("n", "classifier_conditions")
    .rename("x", "summary_variables")
    .convert_dtype("float64", "float32")
)
```

Here is what the adapter is doing:

- `.broadcast("n", to="x")` copies the value of `n` `batch_size` times to ensure that it will also have a dimension `(batch_size,)` even though during simulations it was just a single value that is constant over all simulations within the batch. The batch size is inferred from the shape of `x`.
- `.as_set("n")` indicates that `x` is treated as a set. Their values will be treated as _exchangeable_, meaning that the inference will be the same regardless of their order. 
- `.rename("n", "classifier_conditions")` to make an inference for model comparison, we need to know the sample size. Here, we make sure that `n` is passed directly into the classification network as its condition.
- `.rename("x", "summary_variables")` the data `x` will be passed through a summary network. The output of the summary network will be automatically concatenated with `classifier_conditions` before passing them together into the classification network.

We can now apply the adapter to simulated data to see the results

```{python}
#| ExecuteTime: {end_time: '2025-04-26T02:34:13.930048Z', start_time: '2025-04-26T02:34:13.928375Z'}
processed_data = adapter(data)
for key, value in processed_data.items():
    print(key + " shape:", value.shape)
```

All those shapes are correct now. To summarise, we have

- `model_indices`: The indicators of which model produced the data (one-hot encoded)
- `classifier_conditions`: `n` repeated `batch_size` times
- `summary_variables`: The observations `x` with shape `(100, n, 1)`. The last axis is added by `as_set` such that it can be passed into a summary network

Now we can finally define our networks. 

As a summary network, we will use a simple deep set architecture which is appropriate for summarising exchangeable data. 

As a classification network, we will use a simple multilayer perceptron with 4 hidden layers, each with 32 neurons and SiLU activation function.

```{python}
#| ExecuteTime: {end_time: '2025-04-26T02:34:13.996060Z', start_time: '2025-04-26T02:34:13.974940Z'}
summary_network = bf.networks.DeepSet(summary_dim=8, dropout=None)
classifier_network = bf.networks.MLP(widths=[32] * 4, activation="silu", dropout=None)
```

We can now define our `approximator` consisting of the two networks and the adapter defined above.

```{python}
#| ExecuteTime: {end_time: '2025-04-26T02:34:14.021809Z', start_time: '2025-04-26T02:34:14.019827Z'}
approximator = bf.approximators.ModelComparisonApproximator(
    num_models=2,
    classifier_network=classifier_network,
    summary_network=summary_network,
    adapter=adapter,
    standardize="summary_variables"
)
```

## Training

Now we are ready to train our approximator that will alow us to compare the two models.

To achieve this, we will define a bunch of parameters that indicate how long and on how much data we want the train the models.

```{python}
#| ExecuteTime: {end_time: '2025-04-26T02:34:14.065229Z', start_time: '2025-04-26T02:34:14.063948Z'}
num_batches_per_epoch = 256
batch_size = 128
epochs = 10
```

Then, we define our optimizer, and specify a schedule for its learning rate. In here, we use a `CosineDecay` schedule for `Adam` optimizer.

```{python}
#| ExecuteTime: {end_time: '2025-04-26T02:34:14.118477Z', start_time: '2025-04-26T02:34:14.109925Z'}
learning_rate = keras.optimizers.schedules.CosineDecay(
    initial_learning_rate=1e-4, 
    decay_steps=epochs * num_batches_per_epoch
)
optimizer = keras.optimizers.Adam(learning_rate=learning_rate)
approximator.compile(optimizer=optimizer)
```

And we can fit the networks now!

```{python}
history = approximator.fit(
    epochs=epochs,
    num_batches=num_batches_per_epoch,
    batch_size=batch_size,
    simulator=simulator,
    adapter=adapter,
)
```

Once training has finished, we can visualize the losses.

```{python}
#| ExecuteTime: {end_time: '2025-04-26T02:35:17.051898Z', start_time: '2025-04-26T02:35:16.960475Z'}
f = bf.diagnostics.plots.loss(history=history)
```

## Validation

Once we have trained the model, we can inspect whether the classifier does what we expect it to do. Here, we will generate a validation dataset which has been fixed to generate data of _sample size_ $n=10$. 

```{python}
#| ExecuteTime: {end_time: '2025-04-26T02:35:17.556053Z', start_time: '2025-04-26T02:35:17.058765Z'}
df = simulator.sample(5000, n=10)
print(f"{df['n']=}")
print(f"{df['x'].shape=}")
```

To apply our approximator on this dataset, we simply use the `.predict` method to obtain the predicted posterior model probabilities, given the data and the approximator.

```{python}
#| ExecuteTime: {end_time: '2025-04-26T02:35:17.599619Z', start_time: '2025-04-26T02:35:17.563524Z'}
pred_models = approximator.predict(conditions=df, probs=True)
```

We can inspect the  calibration of posterior model probabilities.

```{python}
#| ExecuteTime: {end_time: '2025-04-26T02:35:17.772515Z', start_time: '2025-04-26T02:35:17.612303Z'}
f = bf.diagnostics.plots.mc_calibration(
    pred_models=pred_models,
    true_models=df["model_indices"],
    model_names=[r"$\mathcal{M}_0$",r"$\mathcal{M}_1$"],
)
```

And the confusion matrix to inspect how often we would make an accurate decision based on picking the model with the highest posterior probability.

```{python}
#| ExecuteTime: {end_time: '2025-04-26T02:35:17.851048Z', start_time: '2025-04-26T02:35:17.784250Z'}
f = bf.diagnostics.plots.mc_confusion_matrix(
    pred_models=pred_models,
    true_models=df["model_indices"],
    model_names=[r"$\mathcal{M}_0$", r"$\mathcal{M}_1$"],
    normalize="true",
)
```

## Saving and Loading

```{python}
from pathlib import Path
```

```{python}
# Recommended - full serialization (checkpoints folder must exist)
filepath = Path("checkpoints") / "ttest_classifier.keras"
filepath.parent.mkdir(exist_ok=True)
approximator.save(filepath=filepath)
```

```{python}
# Load approximator
approximator = keras.saving.load_model(filepath)
```

All the usual methods continue to work on the loaded approximator. For example:

```{python}
pred_models = approximator.predict(conditions=df, probs=True)
```

```{python}
f = bf.diagnostics.plots.mc_calibration(
    pred_models=pred_models,
    true_models=df["model_indices"],
    model_names=[r"$\mathcal{M}_0$",r"$\mathcal{M}_1$"],
)
```


